blank_issues_enabled: false
contact_links:
    - name: ⁉️ Questions
      url: https://github.com/timokoessler/easy-ocsp/discussions/categories/q-a
      about: Please create a discussion for questions or help requests.
