name: 🚀 Feature
description: Suggest a new feature or enhancement
title: '🚀 Feature: '
labels: ['feature']
body:
    - type: markdown
      attributes:
          value: |
              Thanks for suggesting a feature for this project!
    - type: textarea
      id: idea
      attributes:
          label: What is your idea?
          description: Describe the feature or enhancement you are proposing.
          placeholder: What feature would you like to see added to this project? What problem does it solve?
      validations:
          required: true
    - type: checkboxes
      id:
      attributes:
          label: Are you willing to help with the implementation?
          description: If you are willing to help with the implementation, please check the box below.
          options:
              - label: 'Yes'
      validations:
          required: false
