name: Security

on:
    push:
        branches:
            - 'main'
    pull_request:
    schedule:
        - cron: '42 5 * * 2' # Every Tuesday at 5:42am

permissions: {}

jobs:
    zizmor:
        name: Check GitHub Actions
        runs-on: ubuntu-latest
        timeout-minutes: 15
        permissions:
            security-events: write # Required to upload results as security events
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Run zizmor
              uses: zizmorcore/zizmor-action@3dc1ecc9bcb9e94e9b2c709687979e1298497054 # v0.6.2

    codeql:
        name: CodeQL (${{ matrix.language }})
        runs-on: 'ubuntu-latest'
        permissions:
            security-events: write
            packages: read
            actions: read
            contents: read

        strategy:
            fail-fast: false
            matrix:
                include:
                    - language: actions
                      build-mode: none
                    - language: javascript-typescript
                      build-mode: none

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
              with:
                  persist-credentials: false

            - name: Initialize CodeQL
              uses: github/codeql-action/init@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
              with:
                  languages: ${{ matrix.language }}
                  build-mode: ${{ matrix.build-mode }}
                  queries: security-and-quality

            - name: Perform CodeQL Analysis
              uses: github/codeql-action/analyze@5595ccaf912efad79be6eef63a5619ff05969be3 # v4.37.6
              with:
                  category: '/language:${{matrix.language}}'
