name: 🧪 Unit tests

on:
    push:
        branches: ['main']
    pull_request:
permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository ⬇️
              uses: actions/checkout@v6
            - name: Setup Node.js 24 ⚙️
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: 'npm'
            - name: Install dependencies 📦
              run: npm ci
            - name: Run tests 🧪
              run: node --run test:cov
            - name: Upload coverage report to Codecov 📊
              uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5.5.1
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
