name: 🧪 Unit tests

on:
    push:
        branches: ['main']
    pull_request:
permissions:
    contents: read

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository ⬇️
              uses: actions/checkout@v5
            - name: Setup Node.js 24 ⚙️
              uses: actions/setup-node@v6
              with:
                  node-version: 24.x
                  cache: 'npm'
            - name: Install dependencies 📦
              run: npm ci
            - name: Run tests 🧪
              run: npm run test:cov
            - name: Upload coverage report to Codecov 📊
              uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
